name: PR Validation

on:
  pull_request:
    branches:
      - develop

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run HTMLHint for HTML linting
        run: npx htmlhint "*/.html"
      - name: Run Stylelint for CSS linting
        run: npx stylelint "*/.css"
      
  build:
    runs-on: ubuntu-latest
    needs: linting
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build the website with Parcel
        run: npx parcel build src/index.html --no-cache --out-dir dist
